---
   - name: Adding Zabbix ubuntu repo
   - apt_repository: repo deb http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix/ trusty main state present

  name:  Installing zabbix-agent
    - apt:
       name: zabbix-agent
       force: yes
       allow_unauthenticated: yes
       state: latest
       update_cache: yes
       cache_valid_time: 0

  - name: Configure zabbix agent
    template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
    notify:
        restart zabbix-agent
